import assert from 'node:assert/strict';
import test from 'node:test';
import {EthereumReturnPlanner} from '../../../src/adapters/earn/ethereum-return-planner.ts';
import {ETHEREUM_PROFILE} from '../../../src/adapters/earn/vault.ts';
const owner='0x'+'11'.repeat(20),c='0x'+'22'.repeat(20),recipient='0x'+'33'.repeat(20),now=Date.now();
function state(){return{owner,block:{number:10n,hash:'0x'+'aa'.repeat(32),timestamp:BigInt(Math.floor(now/1000)),baseFeePerGas:100n,gasUsed:500n,gasLimit:1000n},usdc:1000000n,eth:1000000000n,weth:0n,shares:0n,nonce:0n,usdcAllowance:0n,shareAllowance:0n,ownerCode:'0x',shareDecimals:18,tips:Array(8).fill(10000n)};}
function planner(s=state()){return new EthereumReturnPlanner({rpcUrl:'https://example.invalid'}, {readState:async()=>s,quote:async r=>({operationId:r.operationId,revision:r.revision,quoteId:'0x'+'bb'.repeat(32),recipient,refundOwner:owner,confidentialAccount:c,amountAtoms:r.amountAtoms,minimumCreditAtoms:'100',expiresAt:Math.floor(now/1000)+120,quotedAtMs:now,chainId:1,token:r.returnAsset==='native'?'0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee':ETHEREUM_PROFILE.usdc,originAsset:'test',providerFeeBps:2}),estimate:async()=>50000n,recipientState:async()=>({code:'0x',balance:0n}),assertFresh:async()=>{}},()=>now);}
test('USDC return budgets exact full balance and subsequent ETH sweep without withdrawing anything',async()=>{const p=await planner().plan({owner,confidentialAccount:c,operationId:'return_1',revision:1,returnAsset:'usdc'});assert.equal(p.amountAtoms,'1000000');assert.equal(p.gasLimit,55000);assert.equal(p.withdrawalReserveWei,(21000n*10112n).toString());assert.equal(p.executionAvailable,false);assert.equal(p.kind,'returnUsdc');});
test('ETH return uses fixed price and full balance minus exactly 21000 gas after USDC is zero',async()=>{await assert.rejects(planner().plan({owner,confidentialAccount:c,operationId:'return_1',revision:1,returnAsset:'native'}));const s=state();s.usdc=0n;const p=await planner(s).plan({owner,confidentialAccount:c,operationId:'return_1',revision:1,returnAsset:'native'});assert.equal(BigInt(p.amountAtoms)+BigInt(p.maximumGasCostWei),s.eth);assert.equal(p.gasLimit,21000);assert.equal(p.priorityFeePerGasWei,'0');assert.equal(p.withdrawalReserveWei,'0');s.shares=1n;await assert.rejects(planner(s).plan({owner,confidentialAccount:c,operationId:'return_2',revision:1,returnAsset:'native'}));});
