import {createPublicClient,http,getAddress,erc20Abi,encodeFunctionData,keccak256,toHex} from 'viem';
import type {Address} from 'viem';
import {mainnet} from 'viem/chains';
import {readEthereumState,type EthereumState,type EthereumPlannerConfig} from './ethereum-deposit-planner.ts';
import {ETHEREUM_PROFILE,balance} from './vault.ts';
import {ceilDiv,feePolicy,nextBaseFee,type Fees} from './policy.ts';
import type {NativeQuoteInput} from './native-gateway.ts';
type ReturnQuote={operationId:string;revision:number;quoteId:string;recipient:string;refundOwner:string;confidentialAccount:string;amountAtoms:string;minimumCreditAtoms:string;expiresAt:number;chainId:number;token:string;providerFeeBps:number};
type Providers={readState:(owner:Address)=>Promise<EthereumState>;quote:(r:NativeQuoteInput)=>Promise<ReturnQuote>;estimate:(owner:Address,recipient:Address,amount:bigint)=>Promise<bigint>;recipientState:(recipient:Address,native:boolean)=>Promise<{code:string;balance:bigint}>;assertFresh:(s:EthereumState,f:Fees)=>Promise<void>};
export class EthereumReturnPlanner{
 private providers:Providers;
 constructor(config:EthereumPlannerConfig,providers:Providers|Pick<Providers,'quote'>,private now:()=>number=Date.now){if('readState'in providers){this.providers=providers;return;}const c=createPublicClient({chain:mainnet,transport:http(config.rpcUrl,{timeout:12000,retryCount:0}),cacheTime:0});this.providers={quote:providers.quote,readState:o=>readEthereumState(c,o,now),estimate:(owner,recipient,amount)=>c.estimateGas({account:owner,to:ETHEREUM_PROFILE.usdc,data:encodeFunctionData({abi:erc20Abi,functionName:'transfer',args:[recipient,amount]})}),recipientState:async(recipient,native)=>({code:(await c.getCode({address:recipient}))??'0x',balance:native?await c.getBalance({address:recipient}):await balance(c,ETHEREUM_PROFILE.usdc,recipient)}),assertFresh:async(s,f)=>{const[latest,pinned,pending]=await Promise.all([readEthereumState(c,getAddress(s.owner),now),c.getBlock({blockNumber:s.block.number}),c.getTransactionCount({address:getAddress(s.owner),blockTag:'pending'})]);if(pinned.hash!==s.block.hash||latest.block.number>s.block.number+1n||nextBaseFee(latest.block)+f.priorityFee>f.depositFee||BigInt(pending)!==s.nonce||['usdc','eth','shares','weth','nonce'].some(k=>latest[k as keyof EthereumState]!==s[k as keyof EthereumState]))throw new Error('Return state changed');}};}
 async plan(r:{owner:string;confidentialAccount:string;operationId:string;revision:number;returnAsset:'usdc'|'native'}){
  const owner=getAddress(r.owner),confidential=getAddress(r.confidentialAccount);if(owner===confidential||!/^[-a-zA-Z0-9_]{1,128}$/.test(r.operationId)||!Number.isSafeInteger(r.revision)||r.revision<1)throw new Error('Invalid return identity');
  const s=await this.providers.readState(owner);if(s.owner.toLowerCase()!==owner.toLowerCase()||s.ownerCode!=='0x'||s.shares!==0n||s.weth!==0n||(r.returnAsset==='native'&&s.usdc!==0n))throw new Error('Return requires a full reconciled withdrawal');const fees=feePolicy(s.block,s.tips),native=r.returnAsset==='native';
  const amount=native?s.eth-21000n*fees.depositFee:s.usdc;if(amount<=0n)throw new Error('Return amount cannot cover current gas');
  const quote=await this.providers.quote({operationId:r.operationId,revision:r.revision,profileChainId:1,sourceOwner:owner,confidentialAccount:confidential,amountAtoms:amount.toString(),returnAsset:r.returnAsset});
  if(quote.operationId!==r.operationId||quote.revision!==r.revision||quote.chainId!==1||quote.amountAtoms!==amount.toString()||quote.confidentialAccount.toLowerCase()!==confidential.toLowerCase()||quote.refundOwner.toLowerCase()!==owner.toLowerCase()||quote.token.toLowerCase()!==(native?'0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee':ETHEREUM_PROFILE.usdc.toLowerCase())||(!Number.isSafeInteger(quote.providerFeeBps)||quote.providerFeeBps<0||quote.providerFeeBps>100)||quote.expiresAt*1000<=this.now())throw new Error('Return quote changed');
  const recipient=getAddress(quote.recipient),target=await this.providers.recipientState(recipient,native);if(target.code!=='0x'||target.balance!==0n||recipient===owner)throw new Error('Return deposit address is not fresh');
  const gas=native?21000n:ceilDiv((await this.providers.estimate(owner,recipient,amount))*110n,100n);if(gas<21000n||gas>3000000n)throw new Error('Invalid return gas');const cost=gas*fees.depositFee,reserve=native?0n:21000n*fees.depositFee;if(s.eth<cost+reserve+(native?amount:0n))throw new Error('Return gas would strand assets');await this.providers.assertFresh(s,fees);
  const quotedAtMs=this.now(),referenceTimestampMs=Number(s.block.timestamp)*1000,expiresAtMs=Math.min(quotedAtMs+45000,referenceTimestampMs+60000,quote.expiresAt*1000);if(expiresAtMs<=quotedAtMs)throw new Error('Return fees expired');
  const plan={kind:native?'returnEth' as const:'returnUsdc' as const,operationId:r.operationId,revision:r.revision,chainId:1,profileId:'ethereum-usdc',owner,confidentialAccount:confidential,refundOwner:owner,quoteId:quote.quoteId,recipient,amountAtoms:amount.toString(),minimumCreditAtoms:quote.minimumCreditAtoms,providerFeeBps:quote.providerFeeBps,nonce:Number(s.nonce),deadline:Math.min(quote.expiresAt,Math.floor(quotedAtMs/1000)+600),gasLimit:Number(gas),maxFeePerGasWei:fees.depositFee.toString(),priorityFeePerGasWei:native?'0':fees.priorityFee.toString(),maximumGasCostWei:cost.toString(),withdrawalReserveWei:reserve.toString(),startingUsdc:s.usdc.toString(),startingNativeWei:s.eth.toString(),startingShares:'0',startingWeth:'0',referenceBlockNumber:s.block.number.toString(),referenceBlockHash:s.block.hash,referenceTimestampMs,quotedAtMs,expiresAtMs,readOnly:true,executionAvailable:false};return{...plan,planHash:keccak256(toHex(JSON.stringify(plan)))};
 }
}
