import {z} from 'zod';
import {EarnRecoveryEnvelope} from './recovery-envelope.ts';
import {createPublicClient,http,erc20Abi,parseAbi,decodeAbiParameters,recoverTypedDataAddress,getAddress,keccak256,toHex,hashTypedData} from 'viem';
import type {Address,Hex} from 'viem';
import {mainnet} from 'viem/chains';
import {FusionQuoteProvider} from './fusion-quote.ts';
import type {FusionProposal} from './fusion-quote.ts';
import {ETHEREUM_PROFILE} from './vault.ts';
const router=getAddress('0x111111125421ca6dc452d289314280a0f8842a65');
const address=z.string().regex(/^0x[0-9a-f]{40}$/i).transform(v=>getAddress(v));
const atoms=z.string().regex(/^[1-9][0-9]{0,77}$/).refine(v=>BigInt(v)<1n<<256n);
const bindingInput=z.object({operationId:z.string().regex(/^[-a-zA-Z0-9_]{1,128}$/),revision:z.number().int().min(1).max(2147483647),quoteId:z.string().regex(/^0x[0-9a-f]{64}$/),recoveryEnvelope:z.string().max(180000).optional()}).strict();
const quoteInput=z.object({operationId:bindingInput.shape.operationId,revision:bindingInput.shape.revision,owner:address,confidentialAccount:address,inputAtoms:atoms,resolverGasPriceWei:atoms,minimumEthWei:atoms,maximumResolverOverheadWei:atoms,executionRequested:z.boolean().optional(),permitData:z.string().regex(/^0x[0-9a-f]{448}$/i).optional(),originalDeadline:z.union([atoms,z.number().int().positive().safe().transform(String)]).optional()}).strict();
const orderSchema=z.object({salt:atoms,maker:address,receiver:address,makerAsset:address,takerAsset:address,makingAmount:atoms,takingAmount:atoms,makerTraits:z.string().regex(/^(0|[1-9][0-9]{0,77})$/)}).strict();
const orderTypes={Order:[{name:'salt',type:'uint256'},{name:'maker',type:'address'},{name:'receiver',type:'address'},{name:'makerAsset',type:'address'},{name:'takerAsset',type:'address'},{name:'makingAmount',type:'uint256'},{name:'takingAmount',type:'uint256'},{name:'makerTraits',type:'uint256'}]};
const orderDomain={name:'1inch Aggregation Router',version:'6',chainId:1,verifyingContract:router};
type Funding={balance:bigint;allowance:bigint;permitNonce:bigint};
type Providers={now?:()=>number;fetcher?:typeof fetch;readFunding?:(owner:Address)=>Promise<Funding>;quote?:(owner:Address,input:bigint,gas:bigint,options?:{permit?:string;enableEstimate?:boolean;deadline?:bigint})=>Promise<FusionProposal>};
export type NativeFusionBinding={operationId:string;revision:number;quoteId:string;owner:Address;confidentialAccount:Address;inputAtoms:string;minimumEthWei:string;grossEthWei:string;deadline:string;quotedAt:number;expiresAt:number;orderHash:string;extensionHash:string;authenticatedBodyHash:string;resolverGasUnits:string;resolverGasPriceWei:string;resolverGasCostWei:string;resolverProfitWei:string;inputValueWei:string;requestedResolverGasPriceWei:string;unsignedOrder:Record<string,string>;extension:string;executable:boolean;recoveryEnvelope?:string};
type Cached={proof:NativeFusionBinding;providerQuoteId:string|null;submitted?:string};
/** Fixed server-key transport. Signatures are accepted only against immutable SDK quotes. */
export class FusionNativeGateway{
 private cache=new Map<string,Cached>();private now:()=>number;private fetcher:typeof fetch;private provider:FusionQuoteProvider;private recovery:EarnRecoveryEnvelope;
 constructor(private config:{apiKey?:string;rpcUrl?:string;recoveryKey?:string},private providers:Providers={}){this.now=providers.now??Date.now;this.fetcher=providers.fetcher??fetch;this.provider=new FusionQuoteProvider(config.apiKey??'',this.fetcher,this.now);this.recovery=new EarnRecoveryEnvelope(config.recoveryKey);}
 private prune(){for(const [key,c]of this.cache)if(c.proof.expiresAt*1000+86400000<this.now())this.cache.delete(key);if(this.cache.size>=512)throw new Error('Native Fusion capacity unavailable');}
 private async funding(owner:Address):Promise<Funding>{if(this.providers.readFunding)return this.providers.readFunding(owner);const c=createPublicClient({chain:mainnet,transport:http(this.config.rpcUrl??'https://ethereum-rpc.publicnode.com',{timeout:12000})});if(await c.getChainId()!==1)throw new Error('Changed Ethereum RPC');const b=await c.getBlock();if(!b.hash||this.now()-Number(b.timestamp)*1000>60000||Number(b.timestamp)*1000-this.now()>5000)throw new Error('Stale Ethereum header');const [balance,allowance,permitNonce]=await Promise.all([c.readContract({address:ETHEREUM_PROFILE.usdc,abi:erc20Abi,functionName:'balanceOf',args:[owner],blockNumber:b.number}),c.readContract({address:ETHEREUM_PROFILE.usdc,abi:erc20Abi,functionName:'allowance',args:[owner,router],blockNumber:b.number}),c.readContract({address:ETHEREUM_PROFILE.usdc,abi:parseAbi(['function nonces(address) view returns(uint256)']),functionName:'nonces',args:[owner],blockNumber:b.number})]);if((await c.getBlock({blockNumber:b.number})).hash!==b.hash)throw new Error('Ethereum reference changed');return{balance,allowance,permitNonce};}
 async quote(body:unknown):Promise<NativeFusionBinding>{this.prune();const r=quoteInput.parse(body);if(!this.config.apiKey||(r.executionRequested&&!this.recovery.configured)||r.owner===r.confidentialAccount)throw new Error('Native Fusion unavailable');const state=await this.funding(r.owner),input=BigInt(r.inputAtoms);if(state.balance<input)throw new Error('Insufficient actual USDC');let deadline:bigint|undefined;
  if(r.permitData){if(r.executionRequested!==true)throw new Error('Private permit requires executable quote');const [permitOwner,spender,value,until,v,rs,ss]=decodeAbiParameters([{type:'address'},{type:'address'},{type:'uint256'},{type:'uint256'},{type:'uint8'},{type:'bytes32'},{type:'bytes32'}],r.permitData as Hex);deadline=until;if(permitOwner.toLowerCase()!==r.owner.toLowerCase()||spender.toLowerCase()!==router.toLowerCase()||value!==input||until<=BigInt(Math.floor(this.now()/1000))||until>BigInt(Math.floor(this.now()/1000)+600)||![27,28].includes(v)||(r.originalDeadline&&BigInt(r.originalDeadline)!==until))throw new Error('Changed USDC permit');const signature=(rs+ss.slice(2)+v.toString(16))as Hex;const recovered=await recoverTypedDataAddress({domain:{name:'USD Coin',version:'2',chainId:1,verifyingContract:ETHEREUM_PROFILE.usdc},types:{Permit:[{name:'owner',type:'address'},{name:'spender',type:'address'},{name:'value',type:'uint256'},{name:'nonce',type:'uint256'},{name:'deadline',type:'uint256'}]},primaryType:'Permit',message:{owner:r.owner,spender:router,value:input,nonce:state.permitNonce,deadline:until},signature});if(recovered.toLowerCase()!==r.owner.toLowerCase())throw new Error('Invalid native USDC permit');
  }else {if(r.executionRequested&&state.allowance<input)throw new Error('An exact native permit or confirmed allowance is required');if(r.originalDeadline){deadline=BigInt(r.originalDeadline);if(deadline<=BigInt(Math.floor(this.now()/1000))||deadline>BigInt(Math.floor(this.now()/1000)+600))throw new Error('Invalid saved order deadline');}}
  const p=await (this.providers.quote??this.provider.quote.bind(this.provider))(r.owner,input,BigInt(r.resolverGasPriceWei),{permit:r.permitData,enableEstimate:r.executionRequested===true,deadline});
  if(p.input!==input||p.minimumEth<BigInt(r.minimumEthWei)||p.economics.allowanceWei>BigInt(r.maximumResolverOverheadWei)||!p.unsignedOrder||!p.extension||p.expiresAtMs<=this.now()||p.quotedAtMs>this.now()+5000||this.now()-p.quotedAtMs>60000||(deadline!==undefined&&p.deadline!==deadline)||(r.executionRequested&&!p.quoteId))throw new Error('Native Fusion bounds changed');
  const quoteId=keccak256(toHex(JSON.stringify({op:r.operationId,revision:r.revision,orderHash:p.orderHash,extension:p.extension,confidentialAccount:r.confidentialAccount})));
  const fields={operationId:r.operationId,revision:r.revision,quoteId,owner:r.owner,confidentialAccount:r.confidentialAccount,inputAtoms:r.inputAtoms,minimumEthWei:p.minimumEth.toString(),grossEthWei:p.grossEth.toString(),deadline:p.deadline.toString(),quotedAt:Math.floor(p.quotedAtMs/1000),expiresAt:Math.floor(p.expiresAtMs/1000),orderHash:p.orderHash,extensionHash:keccak256(p.extension as Hex),resolverGasUnits:p.economics.gasUnits.toString(),resolverGasPriceWei:p.economics.gasPrice.toString(),resolverGasCostWei:p.economics.gasCostWei.toString(),resolverProfitWei:p.economics.profitWei.toString(),inputValueWei:p.economics.inputValueWei.toString(),requestedResolverGasPriceWei:r.resolverGasPriceWei,unsignedOrder:p.unsignedOrder,extension:p.extension,executable:r.executionRequested===true};
  const proof:NativeFusionBinding={...fields,authenticatedBodyHash:keccak256(toHex(JSON.stringify(fields)))};const cached:Cached={proof,providerQuoteId:p.quoteId};
  if(this.recovery.configured)proof.recoveryEnvelope=this.recovery.seal('fusion-order',{issuedAtMs:this.now(),validUntilMs:this.now()+86400000,cached});
  this.cache.set(quoteId,cached);return proof;
 }
 private cached(body:unknown,allowExpired=false){const r=bindingInput.parse(body);let c=this.cache.get(r.quoteId);
  if(!c&&r.recoveryEnvelope){
    const recovered=z.object({issuedAtMs:z.number().safe().int(),validUntilMs:z.number().safe().int(),cached:z.object({proof:z.record(z.string(),z.unknown()),providerQuoteId:z.string().nullable()}).strict()}).strict().parse(this.recovery.open('fusion-order',r.recoveryEnvelope));
    const proof=recovered.cached.proof as unknown as NativeFusionBinding;
    if(recovered.issuedAtMs>this.now()+5000||recovered.validUntilMs<=this.now()||recovered.validUntilMs-recovered.issuedAtMs!==86400000||proof.quoteId!==r.quoteId||proof.operationId!==r.operationId||proof.revision!==r.revision)throw new Error('Changed native Fusion recovery');
    c={proof:{...proof,recoveryEnvelope:r.recoveryEnvelope},providerQuoteId:recovered.cached.providerQuoteId};this.prune();this.cache.set(r.quoteId,c);
  }
  if(!c||c.proof.operationId!==r.operationId||c.proof.revision!==r.revision||(!allowExpired&&c.proof.expiresAt*1000<=this.now()))throw new Error('Native Fusion binding unavailable');return c;}
 binding(body:unknown){return this.cached(body).proof;}
 private async request(path:string,init?:RequestInit){const response=await this.fetcher('https://api.1inch.com/fusion/'+path,{...init,headers:{authorization:`Bearer ${this.config.apiKey}`,'content-type':'application/json'},signal:AbortSignal.timeout(12000)});if(response.status===404)return null;if(!response.ok)throw new Error('Native Fusion provider unavailable');const text=await response.text();if(text.length>250000)throw new Error('Unbounded Fusion response');return text?JSON.parse(text):{};}
 async submit(body:unknown){const r=bindingInput.extend({order:orderSchema,extension:z.string().regex(/^0x(?:[0-9a-f]{2})*$/i).max(65536),signature:z.string().regex(/^0x[0-9a-f]{130}$/i)}).strict().parse(body);const c=this.cached({operationId:r.operationId,revision:r.revision,quoteId:r.quoteId,recoveryEnvelope:r.recoveryEnvelope},true);if(!c.proof.executable||!c.providerQuoteId)throw new Error('Preview cannot be submitted');const expected=orderSchema.parse(c.proof.unsignedOrder);if(JSON.stringify(r.order)!==JSON.stringify(expected)||r.extension.toLowerCase()!==c.proof.extension.toLowerCase())throw new Error('Changed signed Fusion order');const message={...r.order,salt:BigInt(r.order.salt),makingAmount:BigInt(r.order.makingAmount),takingAmount:BigInt(r.order.takingAmount),makerTraits:BigInt(r.order.makerTraits)};const typed={domain:orderDomain,types:orderTypes,primaryType:'Order' as const,message};if(hashTypedData(typed).toLowerCase()!==c.proof.orderHash.toLowerCase()||(await recoverTypedDataAddress({...typed,signature:r.signature as Hex})).toLowerCase()!==c.proof.owner.toLowerCase())throw new Error('Native Fusion signature invalid');const signed=JSON.stringify({order:expected,signature:r.signature,quoteId:c.providerQuoteId,extension:c.proof.extension});if(c.submitted&&c.submitted!==signed)throw new Error('Changed retry payload');if(BigInt(c.proof.deadline)<=BigInt(Math.floor(this.now()/1000)))throw new Error('Expired signed Fusion order');if(!c.submitted&&!r.recoveryEnvelope&&c.proof.expiresAt*1000<=this.now())throw new Error('Expired native quote');c.submitted=signed;await this.request('relayer/v2.0/1/order/submit',{method:'POST',body:signed});return{operationId:r.operationId,revision:r.revision,orderHash:c.proof.orderHash,status:'submitted'};}
 async status(body:unknown){const r=z.object({orderHash:z.string().regex(/^0x[0-9a-f]{64}$/i)}).strict().parse(body);const p=await this.request(`orders/v2.0/1/order/status/${r.orderHash}`)as {status?:string;fills?:{txHash?:string}[]}|null;const status=['pending','filled','expired','cancelled'].includes(p?.status??'')?p!.status!:'unknown';if((p?.fills?.length??0)>100)throw new Error('Unbounded Fusion fills');const fills=(p?.fills??[]).map(f=>{if(!/^0x[0-9a-f]{64}$/i.test(f.txHash??''))throw new Error('Invalid Fusion transaction');return{transactionHash:f.txHash!};});return{orderHash:r.orderHash,status,fills};}
}
