package io.gizu.storedwallet

import java.math.BigDecimal
import java.security.MessageDigest
import org.json.JSONArray
import org.json.JSONObject

/**
 * In-memory authority for one passkey-reviewed native funding manifest. Never persisted. Final
 * paymaster fields are reviewed and constrained by SponsoredEarnOperation; this grant binds the
 * original unsigned request and proposal caps, not future provider-generated bytes.
 */
internal class EarnFundingBatchApproval
private constructor(
  val manifestJson: String,
  private val walletId: String,
  private val generation: String,
  private val cycleIndex: Int,
  private val registry: String,
  private val entries: Map<String, Entry>,
) {
  val digest = fundingBatchDigest(manifestJson)
  private var approvedAt: Long? = null
  private var invalidated = false

  private data class Entry(
    val proposal: String,
    val unsigned: String,
    val allowed: Boolean,
    var authorization: String?,
    var signed: String?,
  )

  companion object {
    private const val LIFETIME_MS = 15 * 60_000L

    fun createManifest(
      rows: List<JSONObject>,
      walletId: String,
      generation: String,
      cycleIndex: Int,
      batchId: String,
      roleRegistry: String,
      ledgerBatch: JSONObject,
    ): EarnFundingBatchApproval {
      check(
        rows.size in 1..256 && cycleIndex >= 0 && walletId.isNotBlank() && generation.isNotBlank()
      )
      requireRoleRegistry(roleRegistry)
      check(batchId.matches(Regex("[-a-zA-Z0-9_]{1,128}")))
      check(
        ledgerBatch.getString("id") == batchId &&
          ledgerBatch.getString("feature") == "earn" &&
          ledgerBatch.getInt("cycleIndex") == cycleIndex &&
          ledgerBatch.getBoolean("registrationComplete")
      ) {
        "Register every funding child before approving the batch"
      }
      val legs =
        ledgerBatch.getJSONArray("legs").let { list ->
          (0 until list.length()).map(list::getJSONObject)
        }
      check(
        legs.size == rows.size &&
          legs.map { it.getInt("sourceIndex") }.distinct().size == legs.size &&
          legs.map { it.getString("operationId") }.distinct().size == legs.size
      )
      val next = JSONObject(roleRegistry).getInt("nextRecipient")
      val indices = mutableSetOf<Int>()
      val ids = mutableSetOf<String>()
      val owners = mutableSetOf<String>()
      val entries = linkedMapOf<String, Entry>()
      val children = JSONArray()
      for (row in rows.sortedBy { it.getJSONObject("proposal").optInt("sourceAccountIndex", 0) }) {
        val p = row.getJSONObject("proposal")
        val id = row.getString("operationId")
        val index = p.optInt("sourceAccountIndex", 0)
        check(index == 0 || index == 1 || index in 3 until next)
        check(indices.add(index) && ids.add(id) && id.matches(Regex("[-a-zA-Z0-9_]{1,128}")))
        check(
          row.getString("walletId") == walletId &&
            p.getString("operationId") == id &&
            p.getString("kind") == "sourceFunding" &&
            p.getInt("chainId") == 143
        )
        check(
          rows.all {
            it.getJSONObject("proposal").getInt("profileChainId") == p.getInt("profileChainId")
          } &&
            p.getInt("profileChainId") in setOf(1, 4663) &&
            p.optInt("cycleIndex", 0) == cycleIndex &&
            p.getString("fundingBatchId") == batchId &&
            p.getInt("fundingBatchSize") == rows.size
        )
        val owner = p.getString("expectedFrom")
        check(
          owner != "0x" + "0".repeat(40) &&
            owner.matches(Regex("0x[0-9a-fA-F]{40}")) &&
            owners.add(owner.lowercase())
        )
        val leg = legs.singleOrNull { it.getInt("sourceIndex") == index }
        check(leg != null)
        check(
          leg.getString("operationId") == id &&
            leg.getString("address").equals(owner, true) &&
            leg.getString("budgetAtoms") == p.getString("budgetAtoms")
        ) {
          "Saved funding proposal does not match its committed reservation"
        }
        val unsigned = row.getJSONObject("unsignedUserOperation")
        check(
          unsigned.getString("sender").equals(owner, true) &&
            (!unsigned.has("signature") || unsigned.getString("signature") == "0x") &&
            !unsigned.has("eip7702Auth")
        )
        check(quantity(p.getString("nonce")) == quantity(unsigned.getString("nonce")))
        val amount = fundingBatchAtoms(p.getString("amountAtoms"))
        val budget = fundingBatchAtoms(p.getString("budgetAtoms"))
        check(
          amount.signum() > 0 &&
            amount +
              fundingBatchAtoms(p.getString("maximumTokenFeeAtoms")) +
              fundingBatchAtoms(p.getString("withdrawalReserveAtoms")) <= budget
        )
        check(
          quantity(unsigned.getString("maxPriorityFeePerGas")) <=
            quantity(unsigned.getString("maxFeePerGas"))
        )
        for (field in
          listOf(
            "callGasLimit",
            "verificationGasLimit",
            "preVerificationGas",
            "maxFeePerGas",
            "maxPriorityFeePerGas",
          )) quantity(unsigned.getString(field))
        val spending = row.sponsoredSpendSaved()
        val allowed =
          !row.optBoolean("cancelled") &&
            !row.optBoolean("conflict") &&
            !row.optBoolean("signingPending") &&
            !leg.optBoolean("cancelled") &&
            !leg.optBoolean("completed") &&
            (if (spending) row.has("signedUserOperation") && row.getString("status") == "signed"
            else row.getString("status") in setOf("planned", "authorizationSaved"))
        val proposal = fundingBatchCanonical(p)
        val original = fundingBatchCanonical(unsigned)
        val authorization =
          row.optJSONObject("authorization")?.let { fundingBatchDigest(fundingBatchCanonical(it)) }
        val signed =
          if (row.has("signedUserOperation"))
            fundingBatchDigest(row.getString("signedUserOperation"))
          else null
        entries[id] = Entry(proposal, original, allowed, authorization, signed)
        children.put(
          JSONObject()
            .put("operationId", id)
            .put("sourceIndex", index)
            .put("owner", owner)
            .put("budgetAtoms", p.getString("budgetAtoms"))
            .put("proposal", JSONObject(proposal))
            .put("originalUnsignedUserOperation", JSONObject(original))
            .put("authorized", allowed)
            .put("authorizationHash", authorization ?: JSONObject.NULL)
            .put("signedUserOperationHash", signed ?: JSONObject.NULL)
        )
      }
      val registry = fundingBatchCanonical(JSONObject(roleRegistry))
      val manifest =
        fundingBatchCanonical(
          JSONObject()
            .put("version", 1)
            .put("walletId", walletId)
            .put("generation", generation)
            .put("cycleIndex", cycleIndex)
            .put("fundingBatchId", batchId)
            .put("roleRegistry", JSONObject(registry))
            .put("children", children)
        )
      check(manifest.toByteArray(Charsets.UTF_8).size <= 3 * 1024 * 1024)
      return EarnFundingBatchApproval(manifest, walletId, generation, cycleIndex, registry, entries)
    }
  }

  /** Caller invokes this only after the passkey challenge bound to digest succeeds. */
  @Synchronized
  fun approveAfterPasskey(now: Long) {
    check(!invalidated && approvedAt == null && now >= 0 && now <= Long.MAX_VALUE - LIFETIME_MS)
    approvedAt = now
  }

  @Synchronized
  fun assertAuthorized(record: WalletRecord, row: JSONObject, now: Long) {
    val started = approvedAt
    check(!invalidated && started != null && now >= started && now - started < LIFETIME_MS) {
      "Funding batch approval expired; review the remaining sources"
    }
    check(
      record.id == walletId &&
        record.journalId == generation &&
        record.verified &&
        !record.earnRecoveryRequired &&
        record.earnCycleIndex == cycleIndex &&
        fundingBatchCanonical(JSONObject(record.roleRegistry)) == registry
    )
    val p = row.getJSONObject("proposal")
    val entry = entries[row.getString("operationId")]
    check(
      entry != null &&
        entry.allowed &&
        row.getString("walletId") == walletId &&
        p.getInt("profileChainId") == record.earnChain
    )
    check(
      !row.optBoolean("cancelled") &&
        !row.optBoolean("conflict") &&
        !row.optBoolean("signingPending") &&
        row.getString("status") !in terminalSteps
    )
    check(
      fundingBatchCanonical(p) == entry.proposal &&
        fundingBatchCanonical(row.getJSONObject("unsignedUserOperation")) == entry.unsigned
    ) {
      "Saved funding terms changed after batch approval"
    }
    // Mutable journal revisions and delegationSaved do not change approved spending terms.
    // Once each native signature is saved, later authority checks require its identical bytes.
    check(!row.has("raw") && !row.has("rawTransaction") && !row.has("signedTransaction"))
    val authorization =
      row.optJSONObject("authorization")?.let { fundingBatchDigest(fundingBatchCanonical(it)) }
    if (entry.authorization != null) check(authorization == entry.authorization)
    val signed =
      if (row.has("signedUserOperation")) fundingBatchDigest(row.getString("signedUserOperation"))
      else null
    if (entry.signed != null) check(signed == entry.signed)
    if (entry.authorization == null && authorization != null) entry.authorization = authorization
    if (entry.signed == null && signed != null) entry.signed = signed
  }

  @Synchronized
  fun invalidate() {
    invalidated = true
    approvedAt = null
  }
}

/** Stable native JSON encoding: sorted object keys, ordered arrays, canonical decimal numbers. */
private fun fundingBatchCanonical(value: Any?): String =
  when (value) {
    null,
    JSONObject.NULL -> "null"
    is JSONObject ->
      value.keys().asSequence().toList().sorted().joinToString(",", "{", "}") { key ->
        JSONObject.quote(key) + ":" + fundingBatchCanonical(value.get(key))
      }
    is JSONArray ->
      (0 until value.length()).joinToString(",", "[", "]") { fundingBatchCanonical(value.get(it)) }
    is String -> JSONObject.quote(value)
    is Boolean -> value.toString()
    is Number -> BigDecimal(value.toString()).stripTrailingZeros().toPlainString()
    else -> error("Unsupported funding manifest value")
  }

private fun fundingBatchDigest(text: String): String =
  "0x" +
    MessageDigest.getInstance("SHA-256").digest(text.toByteArray(Charsets.UTF_8)).joinToString("") {
      "%02x".format(it)
    }

private fun fundingBatchAtoms(value: String): java.math.BigInteger {
  check(value.matches(Regex("0|[1-9][0-9]{0,77}")))
  return value.toBigInteger().also { check(it.bitLength() <= 256) }
}
