import assert from "node:assert/strict";
import { test } from "node:test";
import { privateKeyToAccount } from "viem/accounts";
import { hexToBytes } from "viem";
import { base58 } from "@scure/base";
import { ConfidentialSettlement } from "../../../src/adapters/aurora/settlement.ts";
import { monadUsdcAssetId } from "../../../src/adapters/aurora/assets.ts";
const account=privateKeyToAccount(("0x"+"1".repeat(64)) as `0x${string}`),now=Date.parse("2026-09-30T10:00:00.000Z"),sourceOwner="0x"+"2".repeat(40),depositAddress="0x"+"3".repeat(40),transactionHash="0x"+"a".repeat(64);
const expected={operationId:"fund_1",revision:7,depositAddress,sourceOwner,confidentialAccount:account.address.toLowerCase(),originAsset:monadUsdcAssetId,amountAtoms:"1000000",minimumCreditAtoms:"990000",transactionHash};
async function auth(){const nonce=Buffer.alloc(32);Buffer.from("5628f6c600","hex").copy(nonce);nonce.writeBigUInt64LE(BigInt(now+300000)*1000000n,9);nonce.writeBigUInt64LE(BigInt(now)*1000000n,17);const message={deadline:new Date(now+300000).toISOString(),intents:[],nonce:nonce.toString("base64"),signer_id:account.address.toLowerCase(),verifying_contract:"intents.near"};const payload=JSON.stringify(message),bytes=hexToBytes(await account.signMessage({message:payload}));bytes[64]!-=27;return {standard:"erc191" as const,payload,signature:"secp256k1:"+base58.encode(bytes)};}
function setup(change:(row:Record<string,unknown>)=>void=()=>{}){const calls:{url:string;init?:RequestInit}[]=[];const row:Record<string,unknown>={status:"SUCCESS",depositType:"ORIGIN_CHAIN",recipientType:"CONFIDENTIAL_INTENTS",refundType:"ORIGIN_CHAIN",createdAt:new Date(now-10000).toISOString(),depositAddress,originAsset:monadUsdcAssetId,destinationAsset:monadUsdcAssetId,recipient:account.address.toLowerCase(),refundTo:sourceOwner,amountInFormatted:"1",amountOutFormatted:"0.995",quoteTransactions:[{sender:sourceOwner,txHash:transactionHash}]};change(row);const fetcher:typeof fetch=async(url,init)=>{calls.push({url:String(url),init});return new Response(JSON.stringify(String(url).includes("authenticate")?{accessToken:"SECRET-JWT"}:{items:[{...row,depositAddress:"unrelated",amountOutFormatted:"90000000"},row]}));};return {service:new ConfidentialSettlement("provider-key",fetcher,()=>now),calls};}
test("operation credit comes from authenticated matching history, never aggregate balance or status alone",async()=>{const {service,calls}=setup();const result=await service.read(await auth(),expected);assert.equal(result.status,"credited");assert.equal(result.creditedAtoms,"995000");assert.equal(result.operationScoped,true);assert.equal(result.revision,7);assert.equal(calls.length,2);const history=calls[1]!;assert.ok(history.url.includes("depositAddress="));assert.equal((history.init?.headers as Record<string,string>).Authorization,"Bearer SECRET-JWT");assert.ok(!JSON.stringify(result).includes("SECRET"));});
test("changed asset, C, input, sender/hash, extra deposits and insufficient output cannot prove credit",async()=>{for(const change of [{destinationAsset:"wrong"},{originAsset:"wrong"},{recipient:sourceOwner},{refundTo:depositAddress},{amountInFormatted:"2"},{amountOutFormatted:"0.98"},{amountOutFormatted:"0.9950001"},{quoteTransactions:[{sender:sourceOwner,txHash:"0x"+"b".repeat(64)}]},{quoteTransactions:[{sender:depositAddress,txHash:transactionHash}]},{quoteTransactions:[{sender:sourceOwner,txHash:transactionHash},{sender:depositAddress,txHash:"0x"+"b".repeat(64)}]}])await assert.rejects(setup(row=>Object.assign(row,change)).service.read(await auth(),expected));});
test("processing remains awaiting settlement with zero claimed credit and invalid C fails before provider",async()=>{assert.equal((await setup(row=>row.status="PROCESSING").service.read(await auth(),expected)).status,"awaitingSettlement");const {service,calls}=setup();await assert.rejects(service.read(await auth(),{...expected,confidentialAccount:sourceOwner}));assert.equal(calls.length,0);});
